Vagrant.configure("2") do |config|
  config.vm.box = 'ubuntu/vivid64'
  config.vm.hostname = 'docker-host'

  config.vm.synced_folder '~/workspace/cf-release', '/var/cf-release'

  config.vm.provider 'virtualbox' do |v|
    v.memory = 4096
  end

  config.vm.provision 'docker'

  config.vm.provision 'shell', inline: "echo 'DOCKER_OPTS=\"--storage-driver=devicemapper\"' >> /etc/default/docker"

  # The default machine already has support for SSH
  config.ssh.insert_key = false
  config.ssh.username = 'vagrant'
  # config.ssh.password = "tcuser"

  config.vbguest.auto_update = false
end
