Vagrant.configure("2") do |config|
  config.vm.define "default", autostart: true do |default|
#    default.vm.box = 'ubuntu/trusty64'
    default.vm.box = 'ubuntu/vivid64'

    default.vm.hostname = 'docker-host'
    default.vm.network :forwarded_port, host: 2376, guest: 2376

    default.vm.synced_folder '~/workspace/cf-release', '/var/cf-release'

    default.vm.provider 'virtualbox' do |v|
      v.memory = 4096
    end

    default.vm.provision 'shell', inline: <<-SHELL
      # systemd
      mkdir -p /etc/systemd/system/docker.service.d
      cat > /etc/systemd/system/docker.service.d/storage.conf <<-CONF
        [Service]
        ExecStart=
        ExecStart=/usr/bin/docker daemon -H fd:// --storage-driver=devicemapper
CONF
SHELL

    default.vm.provision 'docker'

    default.vm.provision 'shell', inline: <<-SHELL
      if source /etc/default/docker; then
        echo 'DOCKER_OPTS="$DOCKER_OPTS --storage-driver=devicemapper"' >> /etc/default/docker
        service docker restart
      fi
SHELL

    default.vm.provision 'docker' do |d|
      d.build_image '/vagrant', args: '-t dea-ci'
    end

    # The default machine already has support for SSH
    default.ssh.insert_key = false
    default.ssh.username = 'vagrant'
    # default.ssh.password = "tcuser"

    default.vbguest.auto_update = false
  end

  # config.vm.define "dea" do |app|
  #   app.vm.provider 'docker' do |d|
  #     d.image = 'dea-ci'
  #     d.create_args = ['--privileged', '-ti']
  #     d.volumes = ['/var/cf-release:/cf-release']
  #     #d.has_ssh = true
  #     d.cmd = ['bash']
  #     d.remains_running = false
  #
  #     d.vagrant_vagrantfile = __FILE__
  #   end
  # end
end
