Vagrant.configure("2") do |config|
  config.vm.define "default", autostart: true do |default|
#    default.vm.box = 'ubuntu/trusty64'
    default.vm.box = 'ubuntu/trusty64'

    default.vm.hostname = 'docker-host'
    default.vm.network :forwarded_port, host: 2376, guest: 2376

    default.vm.synced_folder '~/workspace/cf-release', '/var/cf-release'

    default.vm.provider 'virtualbox' do |v|
      v.memory = 4096
    end

    default.vm.provision 'shell', inline: <<-SHELL
      apt-get update && \
      apt-get -y dist-upgrade && \
      apt-get -y install \
        linux-generic-lts-vivid && \
      apt-get update && \
      apt-get -y autoremove && \
      apt-get clean

      # The grub2 configuration is in /etc/default/grub
      if [ -f /etc/default/grub ]; then
        sed -i -e 's/^GRUB_CMDLINE_LINUX=""/GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"/' /etc/default/grub
      fi
SHELL

#     default.vm.provision 'shell', inline: <<-SHELL
#       # systemd
#       mkdir -p /etc/systemd/system/docker.service.d
#       cat > /etc/systemd/system/docker.service.d/storage.conf <<-CONF
#         [Service]
#         ExecStart=
#         ExecStart=/usr/bin/docker daemon -H fd:// --storage-driver=devicemapper
# CONF
# SHELL

    # default.vm.provision 'docker'

#     default.vm.provision 'shell', inline: <<-SHELL
#       if source /etc/default/docker; then
#         echo 'DOCKER_OPTS="$DOCKER_OPTS --storage-driver=devicemapper"' >> /etc/default/docker
#         service docker restart
#       fi
# SHELL

    default.vm.provision 'docker' do |d|
      d.build_image '/vagrant', args: '-t dea-ci'
    end

    default.vm.provision 'shell', inline: <<-SHELL
      shutdown -r now
SHELL

    # The default machine already has support for SSH
    default.ssh.insert_key = false
    default.ssh.username = 'vagrant'
    # default.ssh.password = "tcuser"

    default.vbguest.auto_update = false
  end
end
